### ISSUE TITLE
VA Online Memorial Dummy Data Test

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial#15]
Please check the attached file for dummy data screenshots and the locations.

_Updated: 7:35 PM, Wednesday, April 11, 2018 -_ **Completed**

[VA Online Memorial - 01.zip](https://github.com/topcoderinc/va-online-memorial/files/1901069/VA.Online.Memorial.-.01.zip)

**Comment by dustinWeaver** [comment]
This looks great!  Thank you!

**Comment by MountainGoats** [comment]
Hey hey! Thanks so much for putting this together. I'll work on un-gibberishing (take that Shakespeare) this next week.

**Comment by MountainGoats** [comment]
Helloooooooo!

Here's the breakdown of the "fake to real" language, based on the photos you sent (and a couple of other changes as well). That spreadsheet is attached. Let me know if I made things better, worse, or the same (like an eye doctor). Please and thanks much! 
[VA Online Memorial Document_JT Text.xlsx](https://github.com/topcoderinc/va-online-memorial/files/1916887/VA.Online.Memorial.Document_JT.Text.xlsx)

**Comment by dustinWeaver** [comment]
Thank you @MountainGoats!

**Comment by ksmacleod99** [comment]
Still need to add the link to the blog, we need an icon for it. I am creating a new issue to address this, as well as some additional styling of the footer.
